# Count Vectorizer

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import (
    TfidfVectorizer, CountVectorizer, TfidfTransformer
)

In [2]:
corpus = [
    'this is the first document',
    'this document is the second document',
    'and this is the third one'
]

In [4]:
count_vec = CountVectorizer()
count_vec.fit(corpus)

CountVectorizer()

In [5]:
count_vec.get_feature_names()

['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']

In [7]:
count_data = count_vec.transform(corpus).toarray()
count_data

array([[0, 1, 1, 1, 0, 0, 1, 0, 1],
       [0, 2, 0, 1, 0, 1, 1, 0, 1],
       [1, 0, 0, 1, 1, 0, 1, 1, 1]])

In [9]:
pd.DataFrame(
    data=count_data,
    columns=count_vec.get_feature_names()
)

and  document  first  is  one  second  the  third  this
0    0         1      1   1    0       0    1      0     1
1    0         2      0   1    0       1    1      0     1
2    1         0      0   1    1       0    1      1     1

# Term Frequency Transformer

In [11]:
tf_transformer = TfidfTransformer(use_idf=False)
tf_transformer.fit(count_data)

TfidfTransformer(use_idf=False)

In [13]:
tf_data = tf_transformer.transform(count_data).toarray()
tf_data

array([[0.        , 0.4472136 , 0.4472136 , 0.4472136 , 0.        ,
        0.        , 0.4472136 , 0.        , 0.4472136 ],
       [0.        , 0.70710678, 0.        , 0.35355339, 0.        ,
        0.35355339, 0.35355339, 0.        , 0.35355339],
       [0.40824829, 0.        , 0.        , 0.40824829, 0.40824829,
        0.        , 0.40824829, 0.40824829, 0.40824829]])

In [15]:
pd.DataFrame(
    data=tf_data,
    columns=count_vec.get_feature_names()
)

and  document     first        is       one    second       the  \
0  0.000000  0.447214  0.447214  0.447214  0.000000  0.000000  0.447214   
1  0.000000  0.707107  0.000000  0.353553  0.000000  0.353553  0.353553   
2  0.408248  0.000000  0.000000  0.408248  0.408248  0.000000  0.408248   

      third      this  
0  0.000000  0.447214  
1  0.000000  0.353553  
2  0.408248  0.408248

# Inverse Document Frequency Transformer

In [33]:
tfidf_transformer = TfidfTransformer()
tfidf_transformer.fit(count_data)

TfidfTransformer()

In [34]:
tfidf_data = tfidf_transformer.transform(count_data).toarray()
tfidf_data

array([[0.        , 0.46941728, 0.61722732, 0.3645444 , 0.        ,
        0.        , 0.3645444 , 0.        , 0.3645444 ],
       [0.        , 0.7284449 , 0.        , 0.28285122, 0.        ,
        0.47890875, 0.28285122, 0.        , 0.28285122],
       [0.49711994, 0.        , 0.        , 0.29360705, 0.49711994,
        0.        , 0.29360705, 0.49711994, 0.29360705]])

In [35]:
pd.DataFrame(
    data=tfidf_data,
    columns=count_vec.get_feature_names()
)

and  document     first        is      one    second       the  \
0  0.00000  0.469417  0.617227  0.364544  0.00000  0.000000  0.364544   
1  0.00000  0.728445  0.000000  0.282851  0.00000  0.478909  0.282851   
2  0.49712  0.000000  0.000000  0.293607  0.49712  0.000000  0.293607   

     third      this  
0  0.00000  0.364544  
1  0.00000  0.282851  
2  0.49712  0.293607

# TFIDF Vectorizer

Count Vectorizer --> Tfidf Transformer = Tfidf Vectorizer

In [37]:
tfidf_vec = TfidfVectorizer()
tfidf_vec.fit(corpus)

TfidfVectorizer()

In [38]:
tfidf_data = tfidf_vec.transform(corpus).toarray()

In [39]:
tfidf_vec.get_feature_names()

['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']

In [41]:
pd.DataFrame(
    data=tfidf_data,
    columns=tfidf_vec.get_feature_names()
)

and  document     first        is      one    second       the  \
0  0.00000  0.469417  0.617227  0.364544  0.00000  0.000000  0.364544   
1  0.00000  0.728445  0.000000  0.282851  0.00000  0.478909  0.282851   
2  0.49712  0.000000  0.000000  0.293607  0.49712  0.000000  0.293607   

     third      this  
0  0.00000  0.364544  
1  0.00000  0.282851  
2  0.49712  0.293607